DROP DATABASE biaydcznf4ubkptbgcsb;

CREATE DATABASE biaydcznf4ubkptbgcsb;

USE biaydcznf4ubkptbgcsb;

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USER_USUARIO INT NOT NULL,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    CELULAR_USUARIO CHAR(11) UNIQUE NOT NULL,
    EMAIL_USUARIO VARCHAR(255) NOT NULL,
    LOGRADOURO_USUARIO VARCHAR(100) NOT NULL,
    BAIRRO_USUARIO VARCHAR(30) NOT NULL,
    CIDADE_USUARIO VARCHAR(30) NOT NULL,
    UF_USUARIO CHAR(2) NOT NULL,
    CEP_USUARIO CHAR(8) NOT NULL,
    IMG_URL VARCHAR(255),
    TIPO_USUARIO ENUM ('cliente', 'brechó', 'administrador'),
    STATUS_USUARIO ENUM('ativo', 'inativo', 'banido', 'pendente') DEFAULT 'pendente',
    DESCRICAO_USUARIO TEXT,
    SENHA_USUARIO VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTES (
    ID_USUARIO INT PRIMARY KEY,
    DATA_NASC DATE NOT NULL,
    CPF_CLIENTE CHAR(11) UNIQUE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE BRECHOS (
    ID_USUARIO INT PRIMARY KEY,
    CNPJ_BRECHO CHAR(14) UNIQUE NOT NULL,
    RAZAO_SOCIAL VARCHAR(100) UNIQUE NOT NULL,
    NOME_FANTASIA VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ADMINISTRADORES (
    ID_ADM INT PRIMARY KEY AUTO_INCREMENT,
    CPF_ADM CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PERFIS (
    ID_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    SEGUIDORES INT NOT NULL,
    A_VENDA BOOLEAN NOT NULL,
    VENDIDAS INT NOT NULL,
    DESC_PERFIL VARCHAR(250) NOT NULL,
    IMG_PERFIL_PASTA VARCHAR(255),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    TIPO_PRODUTO VARCHAR(50) NOT NULL,
    TAMANHO_PRODUTO ENUM('XPP', 'PP', 'P', 'M', 'G', 'GG', 'XXG', 'U'),
    COR_PRODUTO VARCHAR(30) NOT NULL,
    CONDICAO_PRODUTO ENUM('novo', 'usado', 'semi-novo') NOT NULL,
    STATUS_PRODUTO ENUM ('disponivel', 'indisponivel'),
    OUTROS TEXT,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

 
CREATE TABLE IMG_PRODUTOS (
    ID_IMG INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    URL_IMG VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);


CREATE TABLE CATEGORIAS_PRODUTOS (
    ID_CATEGORIA_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA_PRODUTO VARCHAR(100) NOT NULL
);


CREATE TABLE PRODUTOS_CATEGORIAS (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORIA_PRODUTO INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
    FOREIGN KEY (ID_CATEGORIA_PRODUTO) REFERENCES CATEGORIAS_PRODUTOS(ID_CATEGORIA_PRODUTO)
);


CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ITEM_PEDIDO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    DT_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('Pendente', 'Concluído', 'Cancelado', 'Enviado') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE AVALIACOES_BRECHOS (
ID_AVALIACAO_BRECHO INT PRIMARY KEY AUTO_INCREMENT,
ID_BRECHO INT NOT NULL,
NOTA INT NOT NULL,
HORA TIME NOT NULL,
COMENTARIO VARCHAR (500),
ID_USUARIO INT NOT NULL,
DT_AVALIACAO DATE NOT NULL,
FOREIGN KEY (ID_BRECHO) REFERENCES BRECHOS(ID_USUARIO)
);

CREATE TABLE ARTIGOS_BLOG (
	ID_ARTIGO INT AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR (255) NOT NULL,
	CONTEUDO TEXT NOT NULL,
	HORA_PUBLICACAO TIME,
	AUTOR VARCHAR(100),
	DT_PUBLICACAO DATE NOT NULL,
	ID_ADM INT NOT NULL,
    DT_ULTIMA_EDICAO DATETIME,
    ID_ADM_EDICAO INT,
    FOREIGN KEY (ID_ADM_EDICAO) REFERENCES ADMINISTRADORES (ID_ADM),
	FOREIGN KEY (ID_ADM) REFERENCES ADMINISTRADORES (ID_ADM)
);

CREATE TABLE CATEGORIAS_BLOG (
ID_CATEGORIA_BLOG INT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA_BLOG VARCHAR(100) NOT NULL
);

CREATE TABLE FAVORITOS (
    ID_FAVORITO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    STATUS_FAVORITO ENUM ('favoritado', 'nulo'),
    TIPO_ITEM ENUM('produto', 'artigo') NOT NULL,
    ID_ITEM INT NOT NULL,
    DATA_FAVORITO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE SACOLA (
    ID_SACOLA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ITENS_SACOLA (
    ID_ITEM_SACOLA INT PRIMARY KEY AUTO_INCREMENT,
    ID_SACOLA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_SACOLA) REFERENCES SACOLA(ID_SACOLA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE BANNERS (
    ID_BANNER INT PRIMARY KEY AUTO_INCREMENT,
    ID_ADM INT NOT NULL,
    URL_IMAGEM VARCHAR(255) NOT NULL,
    LINK_DESTINO VARCHAR(255),
    POSICAO ENUM('Home', 'Blog', 'Categoria') NOT NULL,
    DATA_PUBLICACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ADM) REFERENCES ADMINISTRADORES (ID_ADM)
);

CREATE TABLE DENUNCIAS (
    ID_DENUNCIA INT PRIMARY KEY AUTO_INCREMENT,
    USER_USUARIO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    TIPO_ALVO ENUM('Produto', 'Brecho') NOT NULL,
    ID_ALVO INT NOT NULL,
    MOTIVO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    DATA_DENUNCIA DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS_DENUNCIA ENUM('Aberta', 'Em análise', 'Resolvida', 'Arquivada') DEFAULT 'Aberta',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE DUVIDAS (
    ID_DUVIDA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    PERGUNTA TEXT NOT NULL,
    RESPOSTA TEXT,
    DATA_DUVIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE CUPONS (
    ID_CUPOM INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CUPOM VARCHAR(50) UNIQUE NOT NULL,
    DESCRICAO VARCHAR(255),
    VALOR_DESCONTO DECIMAL(10,2) NOT NULL,
    TIPO_DESCONTO ENUM('Porcentagem', 'Valor Fixo') NOT NULL,
    VALIDADE DATE NOT NULL,
	CRIADO_POR ENUM('ADM','BRECHO') NOT NULL DEFAULT 'ADM',
    ID_ADM INT NULL,
    ID_BRECHO INT NULL, 
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (id_adm) REFERENCES ADMINISTRADORES (id_adm),
    FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_usuario)
);

CREATE INDEX idx_cupom_validade ON CUPONS(VALIDADE);
CREATE INDEX idx_cupom_ativo ON CUPONS(ATIVO);

CREATE TABLE EMAILS (
    ID_EMAIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
	EMAIL_USUARIO VARCHAR(35) UNIQUE NOT NULL,
    ASSUNTO VARCHAR(255) NOT NULL,
    MENSAGEM TEXT NOT NULL,
    DATA_ENVIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE CAIXA (
    ID_MOVIMENTACAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    TIPO_MOVIMENTACAO ENUM('Entrada', 'Saida') NOT NULL,
    PERCENTUAL DECIMAL(10,2) NOT NULL,
	RECEITA DECIMAL(10,2) NOT NULL,
    DESCRICAO VARCHAR(255),
	ID_PRODUTO INT,
    DATA_MOVIMENTACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE ESTATISTICAS (
    ID_EST INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
   -- TOTAL_VENDAS INT DEFAULT 0,
   -- TOTAL_COMPRAS INT DEFAULT 0,
    FATURAMENTO_TOTAL DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);
CREATE VIEW TOTAL_RECEITA_CAIXA AS
SELECT SUM(RECEITA) AS TOTAL_RECEITA FROM CAIXA;

SELECT * FROM TOTAL_RECEITA_CAIXA;

CREATE TABLE GRAFICOS (
    ID_GRAFICO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    MES_REFERENCIA VARCHAR(7) NOT NULL, 
    VENDAS_MES INT DEFAULT 0,
    COMPRAS_MES INT DEFAULT 0,
    FATURAMENTO_MES DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PLANOS (
    ID_PLANO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PLANO VARCHAR(50) NOT NULL,
    DURACAO_DIAS INT NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

INSERT INTO PLANOS (NOME_PLANO, DURACAO_DIAS, PRECO) VALUES
('Basic', 3, 25.00),
('Plus', 7, 50.00),
('Premium', 15, 80.00);

CREATE TABLE ASSINATURAS (
    ID_ASSINATURA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_PLANO INT NOT NULL,
    DATA_INICIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_FIM DATETIME,
    STATUS ENUM('Ativa','Expirada','Cancelada') DEFAULT 'Ativa',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PLANO) REFERENCES PLANOS(ID_PLANO)
);
