CREATE DATABASE biaydcznf4ubkptbgcsb;

USE biaydcznf4ubkptbgcsb;

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USER_USUARIO VARCHAR(255) UNIQUE NOT NULL,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    CELULAR_USUARIO CHAR(15) UNIQUE NOT NULL,
    EMAIL_USUARIO VARCHAR(255) NOT NULL,
    LOGRADOURO_USUARIO VARCHAR(100) NOT NULL,
    NUMERO_USUARIO VARCHAR (4) NOT NULL,
    COMPLEMENTO_USUARIO VARCHAR (100),
    BAIRRO_USUARIO VARCHAR(30) NOT NULL,
    CIDADE_USUARIO VARCHAR(30) NOT NULL,
    UF_USUARIO CHAR(2) NOT NULL,
    CEP_USUARIO CHAR(8) NOT NULL,
    IMG_URL VARCHAR(255),
    TIPO_USUARIO ENUM ('c', 'b', 'a', 'v'),
    STATUS_USUARIO ENUM('a', 'i', 'b', 'p') DEFAULT 'p',
    DESCRICAO_USUARIO VARCHAR(2000),
    SENHA_USUARIO VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTES (
    ID_USUARIO INT PRIMARY KEY,
    DATA_NASC DATE NOT NULL,
    CPF_CLIENTE CHAR(11) UNIQUE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE VENDEDORES_PF (
    ID_USUARIO INT PRIMARY KEY,
    TAXA_COMISSAO_PADRAO DECIMAL(4, 2) DEFAULT 15.00,
    FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO)
);

CREATE TABLE BRECHOS (
    ID_USUARIO INT PRIMARY KEY,
    CNPJ_BRECHO CHAR(14) UNIQUE NOT NULL,
    RAZAO_SOCIAL VARCHAR(100) UNIQUE NOT NULL,
    NOME_FANTASIA VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ADMINISTRADORES (
    ID_ADM INT PRIMARY KEY AUTO_INCREMENT,
    CPF_ADM CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PERFIS (
    ID_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    SEGUIDORES INT NOT NULL,
    A_VENDA BOOLEAN NOT NULL,
    VENDIDAS INT NOT NULL,
    DESC_PERFIL VARCHAR(250) NOT NULL,
    IMG_PERFIL_PASTA VARCHAR(255),
      FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    TIPO_PRODUTO VARCHAR(50) NOT NULL,
    TAMANHO_PRODUTO ENUM('XPP', 'PP', 'P', 'M', 'G', 'GG', 'XXG', 'U'),
    COR_PRODUTO VARCHAR(30) NOT NULL,
    ESTILO_PRODUTO VARCHAR(50) NOT NULL,
    ESTAMPA_PRODUTO VARCHAR(30),
    DETALHES_PRODUTO VARCHAR(150) NOT NULL,
    CONDICAO_PRODUTO ENUM('novo', 'usado', 'semi-novo') NOT NULL,
    STATUS_PRODUTO ENUM ('d', 'i'),
    QUANTIDADE_ESTOQUE INT DEFAULT 1,
    OUTROS TEXT,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
 
CREATE TABLE IMG_PRODUTOS (
    ID_IMG INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    URL_IMG VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE CATEGORIAS_PRODUTOS (
    ID_CATEGORIA_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA_PRODUTO VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUTOS_CATEGORIAS (
    ID_PRODUTO INT NOT NULL,
    ID_CATEGORIA_PRODUTO INT NOT NULL,
    PRIMARY KEY (ID_PRODUTO, ID_CATEGORIA_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
    FOREIGN KEY (ID_CATEGORIA_PRODUTO) REFERENCES CATEGORIAS_PRODUTOS(ID_CATEGORIA_PRODUTO)
);

CREATE TABLE CUPONS (
    ID_CUPOM INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CUPOM VARCHAR(50) UNIQUE NOT NULL,
    DESCRICAO VARCHAR(255),
    VALOR_DESCONTO DECIMAL(10,2) NOT NULL,
    TIPO_DESCONTO ENUM('Porcentagem', 'Valor Fixo') NOT NULL,
    VALIDADE DATE NOT NULL,
	CRIADO_POR ENUM('ADM','BRECHO') NOT NULL DEFAULT 'ADM',
    ID_ADM INT NULL,
    ID_BRECHO INT NULL, 
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (id_adm) REFERENCES ADMINISTRADORES (id_adm),
    FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_usuario)
);

CREATE INDEX idx_cupom_validade ON CUPONS(VALIDADE);
CREATE INDEX idx_cupom_ativo ON CUPONS(ATIVO);


CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    DT_PEDIDO DATETIME NOT NULL,
    ID_CUPOM INT,
    VALOR_FRETE DECIMAL(10, 2),
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    STATUS_PEDIDO ENUM('Pendente', 'Concluído', 'Cancelado', 'Enviado') NOT NULL,
    CODIGO_RASTREIO VARCHAR(50),
    DATA_PREV_ENTREGA DATE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_CUPOM) REFERENCES CUPONS(ID_CUPOM)
);

CREATE VIEW TOTAL_RECEITA_PEDIDOS AS
SELECT 
    SUM(VALOR_TOTAL) AS TOTAL_RECEITA_GERAL,
    COUNT(ID_PEDIDO) AS NUMERO_TOTAL_PEDIDOS_CONCLUIDOS
FROM 
    PEDIDOS
WHERE 
    STATUS_PEDIDO = 'Concluído';

 SELECT * FROM TOTAL_RECEITA_PEDIDOS;

CREATE TABLE AVALIACOES_BRECHOS (
ID_AVALIACAO_BRECHO INT PRIMARY KEY AUTO_INCREMENT,
ID_BRECHO INT NOT NULL,
NOTA INT NOT NULL,
HORA TIME NOT NULL,
COMENTARIO VARCHAR (500),
ID_USUARIO INT NOT NULL,
DT_AVALIACAO DATE NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES CLIENTES(ID_USUARIO),
FOREIGN KEY (ID_BRECHO) REFERENCES BRECHOS(ID_USUARIO)
);

CREATE TABLE ARTIGOS_BLOG (
	ID_ARTIGO INT AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR (255) NOT NULL,
	CONTEUDO TEXT NOT NULL,
	HORA_PUBLICACAO TIME,
	AUTOR VARCHAR(100),
	DT_PUBLICACAO DATE NOT NULL,
	ID_ADM INT NOT NULL,
    ID_CATEGORIA_BLOG INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA_BLOG) REFERENCES CATEGORIAS_BLOG (ID_CATEGORIA_BLOG),
	FOREIGN KEY (ID_ADM) REFERENCES ADMINISTRADORES (ID_ADM)
);

CREATE TABLE CATEGORIAS_BLOG (
ID_CATEGORIA_BLOG INT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA_BLOG VARCHAR(100) NOT NULL
);

CREATE TABLE FAVORITOS (
    ID_FAVORITO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    STATUS_FAVORITO ENUM ('favoritado', 'nulo'),
    TIPO_ITEM ENUM('produto', 'artigo') NOT NULL,
    ID_ITEM INT NOT NULL,
    DATA_FAVORITO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE SACOLA (
    ID_SACOLA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ITENS_SACOLA (
    ID_ITEM_SACOLA INT PRIMARY KEY AUTO_INCREMENT,
    ID_SACOLA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    TAMANHO_SELECIONADO ENUM('XPP', 'PP', 'P', 'M', 'G', 'GG', 'XXG', 'U'),
     QUANTIDADE INT NOT NULL DEFAULT 1,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_SACOLA) REFERENCES SACOLA(ID_SACOLA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE BANNERS (
    ID_BANNER INT PRIMARY KEY AUTO_INCREMENT,
    ID_ADM INT NOT NULL,
    URL_IMAGEM VARCHAR(255) NOT NULL,
    LINK_DESTINO VARCHAR(255),
    POSICAO ENUM('Home', 'Blog', 'Categoria') NOT NULL,
    DATA_PUBLICACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ADM) REFERENCES ADMINISTRADORES (ID_ADM)
);

CREATE TABLE RELATAR (
    ID_RELATO INT PRIMARY KEY AUTO_INCREMENT,
    USER_USUARIO VARCHAR(255) NOT NULL,
    ID_USUARIO INT NOT NULL,
    TIPO_ALVO ENUM('Produto', 'Brecho') NOT NULL,
    ID_ALVO INT NOT NULL,
    MOTIVO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    DATA_RELATO DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS_RELATO ENUM('Aberta', 'Em análise', 'Resolvida', 'Arquivada') DEFAULT 'Aberta',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE DUVIDAS (
    ID_DUVIDA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    PERGUNTA TEXT NOT NULL,
    RESPOSTA TEXT,
    DATA_DUVIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE SUGESTOES (
    ID_SUGESTAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
	SUGESTAO_USUARIO VARCHAR(35) UNIQUE NOT NULL,
    ASSUNTO VARCHAR(255) NOT NULL,
    MENSAGEM TEXT NOT NULL,
    DATA_ENVIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE CAIXA (
    ID_MOVIMENTACAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    TIPO_MOVIMENTACAO ENUM('Entrada', 'Saida') NOT NULL,
    PERCENTUAL DECIMAL(10,2) NOT NULL,
	RECEITA DECIMAL(10,2) NOT NULL,
    DESCRICAO VARCHAR(255),
	ID_PRODUTO INT,
    DATA_MOVIMENTACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE VIEW TOTAL_RECEITA_CAIXA AS
SELECT SUM(RECEITA) AS TOTAL_RECEITA FROM CAIXA;

SELECT * FROM TOTAL_RECEITA_CAIXA;

CREATE TABLE ESTATISTICAS (
    ID_EST INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    FATURAMENTO_TOTAL DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);

CREATE VIEW FATURAMENTO_ACUMULADO_POR_USUARIO AS
SELECT
    ID_USUARIO,
    SUM(CASE WHEN TIPO_MOVIMENTACAO = 'Entrada' THEN RECEITA ELSE 0 END) AS RECEITA_TOTAL_ACUMULADA,
    SUM(CASE WHEN TIPO_MOVIMENTACAO = 'Saida' THEN RECEITA ELSE 0 END) AS DESPESA_TOTAL_ACUMULADA
FROM 
    CAIXA
GROUP BY 
    ID_USUARIO; 

 SELECT * FROM FATURAMENTO_ACUMULADO_POR_USUARIO;

CREATE TABLE GRAFICOS (
    ID_GRAFICO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    MES_REFERENCIA VARCHAR(7) NOT NULL, 
	ANO_REFERENCIA CHAR(4) NOT NULL, 
    VENDAS_MES INT DEFAULT 0,
    COMPRAS_MES INT DEFAULT 0,
    FATURAMENTO_MES DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE VIEW FATURAMENTO_MENSAL AS
SELECT
    ID_USUARIO,
    DATE_FORMAT(DATA_MOVIMENTACAO, '%Y-%m') AS MES_REFERENCIA, -- Cria o campo 'AAAA-MM'
    SUM(CASE WHEN TIPO_MOVIMENTACAO = 'Entrada' THEN RECEITA ELSE 0 END) AS FATURAMENTO_MES
FROM 
    CAIXA
GROUP BY 
    ID_USUARIO, MES_REFERENCIA
ORDER BY 
    ID_USUARIO, MES_REFERENCIA DESC;

 SELECT * FROM FATURAMENTO_MENSAL;

CREATE VIEW VENDAS_MENSAL AS
SELECT
    ID_USUARIO,
    DATE_FORMAT(DT_PEDIDO, '%Y-%m') AS MES_REFERENCIA,
    COUNT(ID_PEDIDO) AS VENDAS_MES
FROM 
    PEDIDOS
WHERE 
    STATUS_PEDIDO = 'Concluído'
GROUP BY 
    ID_USUARIO, MES_REFERENCIA
ORDER BY 
    ID_USUARIO, MES_REFERENCIA DESC;

SELECT * FROM VENDAS_MENSAL;

CREATE TABLE PLANOS (
    ID_PLANO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PLANO VARCHAR(50) NOT NULL,
    DURACAO_DIAS INT NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

INSERT INTO PLANOS (NOME_PLANO, DURACAO_DIAS, PRECO) VALUES
('Basic', 3, 25.00),
('Plus', 7, 50.00),
('Premium', 15, 80.00);

CREATE TABLE ASSINATURAS (
    ID_ASSINATURA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_PLANO INT NOT NULL,
    DATA_INICIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_FIM DATETIME,
    STATUS ENUM('A','E','C') DEFAULT 'A',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PLANO) REFERENCES PLANOS(ID_PLANO)
);